# Dependabot configuration for NexusSynth
version: 2

updates:
  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "nexussynth-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # CMake and C++ dependencies monitoring
  # Note: Dependabot doesn't directly support CMake/CPM, but we monitor
  # the package ecosystems that our dependencies come from
  
  # Docker dependencies (if we add containerization later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"

  # Python dependencies for CI/CD scripts
  - package-ecosystem: "pip"
    directory: "/.github/scripts"
    schedule:
      interval: "weekly"
      day: "wednesday"  
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"